name: CI/CD Pipeline
on: workflow_dispatch
env:
    AWS_REGION: us-west-1
    REGISTRY: 158897922573.dkr.ecr.us-east-1.amazonaws.com/
    ECR_REPOSITORY: vprofileapp
    EKS_CLUSTER: 

jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Code CHeckout
              uses: actions/checkout@v4

            - name: Maven Test
              id: test
              run: mvn test

            - name: Checkstyle
              run: mvn  checkstyle:checkstyle 

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            
            - name: Setup Sonarqube
              run: sonar-scanner
                    -Dsonar.host.url=${{secrets.SONAR_URL}}
                    -Dsonar.login=${{secrets.SONAR_TOKEN}}
                    -Dsonar.organization=${{ secrets.SONAR_ORGANISATION }} 
                    -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}              
                    -Dsonar.sources=src/
                    -Dsonar.junit.reportsPath=./target/surefire-reports/
                    -Dsonar.jacoco.reportPaths=./target/jacoco.exec
                    -Dsonar.java.checkstyle.reportPaths=./target/checkstyle-result.xml
                    -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
            
            - name: Sonarqube Quality Gate
              id: sonarqube-quality-gate-check
              uses: sonarsource/sonarqube-quality-gate-action@master
              timeout-minutes: 5
              env:
                 SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                 SONAT_HOST_URL: ${{ secrets.SONAR_URL }}